# Generated by Django 5.0.3 on 2024-05-12 12:36

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_type', models.CharField()),
                ('group_type', models.CharField()),
                ('sequence_type', models.CharField()),
                ('note_duration', models.PositiveIntegerField()),
                ('instrument', models.CharField()),
                ('pitch_range', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('result', models.BooleanField()),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
